[project]
name = "rg_calf"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "goalagent",
    "mlflow>=2.21.2",
    "rg_port",
]

[tool.uv.sources]
goalagent = { workspace = true }
rg_port = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
